<a href="https://colab.research.google.com/github/supriyasri/PYTHON-MANIA-/blob/master/Numpy_practise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
print(np.__version__)
np.show_config()

1.16.3
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blis_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
lapack_mkl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE


In [0]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [0]:
b=np.arange(30)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [0]:
b[::-5]           #start from index -1,stop at every index of five and goes on till the end of array

array([29, 24, 19, 14,  9,  4])

In [0]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [0]:
b[::-1]               #start from index -1,stop at every index of one and goes on till the end of array

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [0]:
sample=np.random.rand(3,5)               #shape argument is seperate one.  
print(sample)

[[0.57727769 0.2513681  0.65662933 0.68092406 0.63756157]
 [0.35452609 0.95272935 0.19820389 0.23271298 0.5953399 ]
 [0.36487581 0.54141563 0.90649045 0.30298636 0.20684795]]


In [0]:
a=np.random.random_sample(3,5)

TypeError: ignored

In [0]:
a=np.random.random_sample((3,5))         #shape argument is a single tuple   
a

array([[0.52428607, 0.86412263, 0.76175636, 0.18377275, 0.71648709],
       [0.84483964, 0.77417314, 0.8478764 , 0.85596487, 0.99224541],
       [0.53457397, 0.50770879, 0.06707065, 0.30435872, 0.04339156]])

In [15]:
pyString = 'Android'

# contains indices (0, 1, 2)
# i.e. A, n and d
sObject = slice(3)

print(pyString[sObject])
print(pyString[-1:-3])

# contains indices fromonetofive Get substring from a given string using slice object
# i.e. n, r 
sObject = slice(1, 5)

print(pyString[sObject])

And

ndro


In [39]:
 pyString= 'supriya'
 sObject = slice(-5)
print(pyString(sObject))         #try to use square brackets while defifnin sObject

TypeError: ignored

In [42]:
pyString = 'Android'
sObject=slice(-1,-2,-3)

print(pyString[sObject])

d


In [26]:
pyString = 'Python'
print(pyString[1:5:2])     #start at 1,stop at 5 and update for every 2

yh


In [45]:
 pyString= 'supriya'    
 sObject = slice(-5)         #Slice(1) = indices (0)	
                             #Slice (2) = indices (0,1)	
                             #Slice (3) = indices (0,1,2)	
	
                             # In this case,	Slice (-5) = slice (2) = indices (0,1)	
print(pyString[sObject])   

pyString = 'Android'

# contains indices (0, 1, 2)-startsat index 0 and ends at 2
# i.e. A, n and d
sObject = slice(3)          

print(pyString[sObject])

su
And


In [47]:
pyList= ['s','u','p','r','i','y','a']           #extract sublist and subtuplefromgiven list [] and tuple()
pyTuple=('b','a','b','y','a','m','a','r')

sobject=slice(-2)
print(pyList[sobject])
print(pyTuple[sobject])


['s', 'u', 'p', 'r', 'i']
('b', 'a', 'b', 'y', 'a', 'm')
